// <auto-generated />
using System;
using System.Collections.Generic;
using ElecWasteCollection.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElecWasteCollection.Infrastructure.Migrations
{
    [DbContext(typeof(ElecWasteCollectionDbContext))]
    [Migration("20260101092802_Change_AssignLogic_FromPackage_To_SCP")]
    partial class Change_AssignLogic_FromPackage_To_SCP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFirstLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.AttributeOptions", b =>
                {
                    b.Property<Guid>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<double?>("EstimateVolume")
                        .HasColumnType("double precision");

                    b.Property<double?>("EstimateWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("OptionId");

                    b.HasIndex("AttributeId");

                    b.ToTable("AttributeOptions", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Attributes", b =>
                {
                    b.Property<Guid>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AttributeId");

                    b.ToTable("Attributes", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.CategoryAttributes", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryAttributeId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoryId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("CategoryAttributes", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.CollectionGroups", b =>
                {
                    b.Property<int>("CollectionGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CollectionGroupId"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Group_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shift_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CollectionGroupId");

                    b.HasIndex("Shift_Id");

                    b.ToTable("CollectionGroups", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.CollectionRoutes", b =>
                {
                    b.Property<Guid>("CollectionRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("Actual_Time")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("CollectionDate")
                        .HasColumnType("date");

                    b.Property<int>("CollectionGroupId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ConfirmImages")
                        .HasColumnType("text[]");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<TimeOnly>("EstimatedTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectMessage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CollectionRouteId");

                    b.HasIndex("CollectionGroupId");

                    b.HasIndex("ProductId");

                    b.ToTable("CollectionRoutes", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CompanyId");

                    b.HasIndex("Created_At");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.ForgotPassword", b =>
                {
                    b.Property<Guid>("ForgotPasswordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ForgotPasswordId");

                    b.HasIndex("UserId");

                    b.ToTable("ForgotPassword", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Packages", b =>
                {
                    b.Property<string>("PackageId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmallCollectionPointsId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PackageId");

                    b.HasIndex("SmallCollectionPointsId");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.PointTransactions", b =>
                {
                    b.Property<Guid>("PointTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Point")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PointTransactionId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("PointTransactions", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AssignedSmallPointId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("CheckMessage")
                        .HasColumnType("text[]");

                    b.Property<string>("CollectionCompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("DistanceToPointKm")
                        .HasColumnType("double precision");

                    b.Property<double>("EstimatePoint")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectMessage")
                        .HasColumnType("text");

                    b.Property<string>("ScheduleJson")
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PostId");

                    b.HasIndex("AssignedSmallPointId");

                    b.HasIndex("CollectionCompanyId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SenderId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.ProductImages", b =>
                {
                    b.Property<Guid>("ProductImagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiDetectedLabelsJson")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductImagesId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.ProductStatusHistory", b =>
                {
                    b.Property<Guid>("ProductStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductStatusHistoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductStatusHistory", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.ProductValues", b =>
                {
                    b.Property<Guid>("ProductValuesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttributeOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ProductValuesId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductValues", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Products", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("CreateAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageId")
                        .HasColumnType("text");

                    b.Property<string>("QRCode")
                        .HasColumnType("text");

                    b.Property<string>("SmallCollectionPointId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isChecked")
                        .HasColumnType("boolean");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreateAt");

                    b.HasIndex("PackageId");

                    b.HasIndex("QRCode")
                        .IsUnique();

                    b.HasIndex("SmallCollectionPointId");

                    b.HasIndex("UserId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Shifts", b =>
                {
                    b.Property<string>("ShiftId")
                        .HasColumnType("text");

                    b.Property<Guid>("CollectorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Shift_End_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Shift_Start_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vehicle_Id")
                        .HasColumnType("text");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("ShiftId");

                    b.HasIndex("CollectorId");

                    b.HasIndex("Vehicle_Id");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.SmallCollectionPoints", b =>
                {
                    b.Property<string>("SmallCollectionPointsId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OpenTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecyclingCompanyId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SmallCollectionPointsId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Created_At");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RecyclingCompanyId");

                    b.ToTable("SmallCollectionPoints", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<Guid>("SystemConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmallCollectionPointId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SystemConfigId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SmallCollectionPointId");

                    b.ToTable("SystemConfig", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppleId")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("CollectionCompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmallCollectionPointId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("CollectionCompanyId");

                    b.HasIndex("CreateAt");

                    b.HasIndex("SmallCollectionPointId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.UserAddress", b =>
                {
                    b.Property<Guid>("UserAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Iat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ing")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isDefault")
                        .HasColumnType("boolean");

                    b.HasKey("UserAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.UserPoints", b =>
                {
                    b.Property<Guid>("UserPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Points")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserPointId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPoints", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Vehicles", b =>
                {
                    b.Property<string>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("Capacity_Kg")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity_M3")
                        .HasColumnType("integer");

                    b.Property<string>("Plate_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Small_Collection_Point")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vehicle_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleId");

                    b.HasIndex("Small_Collection_Point");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Account", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Account_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.AttributeOptions", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Attributes", "Attribute")
                        .WithMany("AttributeOptions")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttributeOptions_Attribute");

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Brand", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Category", "Category")
                        .WithMany("Brands")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Brand_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Category", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .HasConstraintName("FK_Category_ParentCategory");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.CategoryAttributes", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Attributes", "Attribute")
                        .WithMany("CategoryAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CategoryAttributes_Attribute");

                    b.HasOne("ElecWasteCollection.Domain.Entities.Category", "Category")
                        .WithMany("CategoryAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CategoryAttributes_Category");

                    b.Navigation("Attribute");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.CollectionGroups", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Shifts", "Shifts")
                        .WithMany("CollectionGroups")
                        .HasForeignKey("Shift_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CollectionGroups_Shifts");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.CollectionRoutes", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.CollectionGroups", "CollectionGroup")
                        .WithMany("CollectionRoutes")
                        .HasForeignKey("CollectionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CollectionRoutes_CollectionGroups");

                    b.HasOne("ElecWasteCollection.Domain.Entities.Products", "Product")
                        .WithMany("CollectionRoutes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CollectionRoutes_Products");

                    b.Navigation("CollectionGroup");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.ForgotPassword", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.User", "User")
                        .WithMany("ForgotPasswords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ForgotPassword_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Packages", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.SmallCollectionPoints", "SmallCollectionPoints")
                        .WithMany("Packages")
                        .HasForeignKey("SmallCollectionPointsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Packages_SmallCollectionPoints");

                    b.Navigation("SmallCollectionPoints");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.PointTransactions", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Products", "Product")
                        .WithMany("PointTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PointTransactions_Product");

                    b.HasOne("ElecWasteCollection.Domain.Entities.User", "User")
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PointTransactions_User");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Post", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.SmallCollectionPoints", "AssignedSmallPoint")
                        .WithMany("Posts")
                        .HasForeignKey("AssignedSmallPointId")
                        .HasConstraintName("FK_Post_SmallCollectionPoints");

                    b.HasOne("ElecWasteCollection.Domain.Entities.Company", "CollectionCompany")
                        .WithMany("Posts")
                        .HasForeignKey("CollectionCompanyId")
                        .HasConstraintName("FK_Post_CollectionCompany");

                    b.HasOne("ElecWasteCollection.Domain.Entities.Products", "Product")
                        .WithMany("Posts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Post_Products");

                    b.HasOne("ElecWasteCollection.Domain.Entities.User", "Sender")
                        .WithMany("Posts")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Post_User");

                    b.Navigation("AssignedSmallPoint");

                    b.Navigation("CollectionCompany");

                    b.Navigation("Product");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.ProductImages", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Products", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductImages_Products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.ProductStatusHistory", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Products", "Product")
                        .WithMany("ProductStatusHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductStatusHistory_Products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.ProductValues", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Attributes", "Attribute")
                        .WithMany("ProductValues")
                        .HasForeignKey("AttributeId")
                        .HasConstraintName("FK_ProductValues_Attribute");

                    b.HasOne("ElecWasteCollection.Domain.Entities.Products", "Product")
                        .WithMany("ProductValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductValues_Products");

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Products", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Brand");

                    b.HasOne("ElecWasteCollection.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Category");

                    b.HasOne("ElecWasteCollection.Domain.Entities.Packages", "Package")
                        .WithMany("Products")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_Products_Packages");

                    b.HasOne("ElecWasteCollection.Domain.Entities.SmallCollectionPoints", "SmallCollectionPoint")
                        .WithMany("Products")
                        .HasForeignKey("SmallCollectionPointId")
                        .HasConstraintName("FK_Products_SmallCollectionPoints");

                    b.HasOne("ElecWasteCollection.Domain.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Products_User");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Package");

                    b.Navigation("SmallCollectionPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Shifts", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.User", "Collector")
                        .WithMany("Shifts")
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Shifts_User");

                    b.HasOne("ElecWasteCollection.Domain.Entities.Vehicles", "Vehicle")
                        .WithMany("Shifts")
                        .HasForeignKey("Vehicle_Id")
                        .HasConstraintName("FK_Shifts_Vehicles");

                    b.Navigation("Collector");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.SmallCollectionPoints", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Company", "CollectionCompany")
                        .WithMany("SmallCollectionPoints")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SmallCollectionPoints_CollectionCompany");

                    b.HasOne("ElecWasteCollection.Domain.Entities.Company", "RecyclingCompany")
                        .WithMany("AssignedRecyclingPoints")
                        .HasForeignKey("RecyclingCompanyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SmallCollectionPoints_RecyclingCompany");

                    b.Navigation("CollectionCompany");

                    b.Navigation("RecyclingCompany");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.SystemConfig", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Company", "Company")
                        .WithMany("CustomSettings")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_SystemConfig_Company");

                    b.HasOne("ElecWasteCollection.Domain.Entities.SmallCollectionPoints", "SmallCollectionPoint")
                        .WithMany("CustomSettings")
                        .HasForeignKey("SmallCollectionPointId")
                        .HasConstraintName("FK_SystemConfig_SmallCollectionPoints");

                    b.Navigation("Company");

                    b.Navigation("SmallCollectionPoint");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.User", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.Company", "CollectionCompany")
                        .WithMany("Users")
                        .HasForeignKey("CollectionCompanyId")
                        .HasConstraintName("FK_User_CollectionCompany");

                    b.HasOne("ElecWasteCollection.Domain.Entities.SmallCollectionPoints", "SmallCollectionPoint")
                        .WithMany("Users")
                        .HasForeignKey("SmallCollectionPointId")
                        .HasConstraintName("FK_User_SmallCollectionPoints");

                    b.Navigation("CollectionCompany");

                    b.Navigation("SmallCollectionPoint");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAddress_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.UserPoints", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.User", "User")
                        .WithMany("UserPoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserPoints_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Vehicles", b =>
                {
                    b.HasOne("ElecWasteCollection.Domain.Entities.SmallCollectionPoints", "SmallCollectionPoints")
                        .WithMany("Vehicles")
                        .HasForeignKey("Small_Collection_Point")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_SmallCollectionPoints");

                    b.Navigation("SmallCollectionPoints");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Attributes", b =>
                {
                    b.Navigation("AttributeOptions");

                    b.Navigation("CategoryAttributes");

                    b.Navigation("ProductValues");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Category", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("CategoryAttributes");

                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.CollectionGroups", b =>
                {
                    b.Navigation("CollectionRoutes");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Company", b =>
                {
                    b.Navigation("AssignedRecyclingPoints");

                    b.Navigation("CustomSettings");

                    b.Navigation("Posts");

                    b.Navigation("SmallCollectionPoints");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Packages", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Products", b =>
                {
                    b.Navigation("CollectionRoutes");

                    b.Navigation("PointTransactions");

                    b.Navigation("Posts");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductStatusHistories");

                    b.Navigation("ProductValues");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Shifts", b =>
                {
                    b.Navigation("CollectionGroups");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.SmallCollectionPoints", b =>
                {
                    b.Navigation("CustomSettings");

                    b.Navigation("Packages");

                    b.Navigation("Posts");

                    b.Navigation("Products");

                    b.Navigation("Users");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("ForgotPasswords");

                    b.Navigation("PointTransactions");

                    b.Navigation("Posts");

                    b.Navigation("Products");

                    b.Navigation("Shifts");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserPoints");
                });

            modelBuilder.Entity("ElecWasteCollection.Domain.Entities.Vehicles", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
